### ISSUE TITLE
Scan function should poll stream and re-balance new shards

### ISSUE THREAD

**Issue by harlow** [harlow/kinesis-consumer#36]
Currently when the `Scan` function runs it queries Kinesis for each of the shard names and automatically starts processing them. However, if a user were to manually change the shard count from 2 to 3 the current implementation wouldn't process the new shard until the application is restarted.

Additional functionality:

1. poll kinesis for new/removed shards
2. kick off new process for new shards
3. make sure if a shard is removed the program handless it gracefully (and continues processing the old shards)

**Comment by vincent6767** [comment]
@harlow 
A question. How do you handle the polling?

**Comment by harlow** [comment]
> A question. How do you handle the polling?

I suspect it would need to be in a goroutine w/ a ticker that checks the available shards every few seconds.

**Comment by vincent6767** [comment]
@harlow 
Turns out that we are able to detect the re-sharding by using the `NextShardIterator` field as documented [here](https://docs.aws.amazon.com/streams/latest/dev/kinesis-using-sdk-java-after-resharding.html#kinesis-using-sdk-java-resharding-data-routing). What do you think if we check for the new shards only if there is a closed shard instead of polling every X seconds? A closed shard indicates a re-sharding event has occurred.

**Comment by imaramos** [comment]
Hello @harlow, I am also facing this issue, do you have devolpment on this?
Thank you.

**Comment by harlow** [comment]
I have a wip branch that still needs some work and lots of testing:
https://github.com/harlow/kinesis-consumer/compare/hw-reshard?expand=1

hopefully will have something up for review in next few days
