### ISSUE TITLE
I've got syntax error: unexpected = in type declaration

### ISSUE THREAD

**Issue by sinnawat** [harlow/kinesis-consumer#41]
I've got error while installation.
`
github.com/harlow/kinesis-consumer/consumer.go:14: syntax error: unexpected = in type declaration
`

Is your code are required GO Version 1.9+?

**Comment by harlow** [comment]
Hi @sinnawat yes this leverage Go 1.9 type aliases
https://golang.org/doc/go1.9#language

```go
// Record is an alias of record returned from kinesis library
type Record = kinesis.Record
```

I chose to do this so the consumer application didn't need to explicitly import the aws library when using the `Scan` function:
https://github.com/harlow/kinesis-consumer/blob/master/consumer.go#L114

```go
err = c.Scan(context.TODO(), func(r *consumer.Record) bool {
  fmt.Println(string(r.Data))
  eturn true // continue scanning
})
```

Instead of:

```go
err = c.Scan(context.TODO(), func(r *kinesis.Record) bool {
  fmt.Println(string(r.Data))
  eturn true // continue scanning
})
```

**Comment by harlow** [comment]
I'll close this for the time being; if the 1.9 dependency is an issue I could be open to the discussion of removing the type alias. It may very well be a case of [YAGNI](https://martinfowler.com/bliki/Yagni.html).
